import { prisma } from "@/lib/db";
import { notFound } from "next/navigation";
import PortfolioView from "@/components/portfolio/PortfolioView";
import type { PortfolioData } from "@/lib/types";
import type { Metadata } from "next";

interface PageProps {
  params: Promise<{ id: string }>;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { id } = await params;
  const portfolio = await prisma.portfolio.findUnique({ where: { id } });

  if (!portfolio || portfolio.revoked) {
    return { title: "Portfolio Not Found" };
  }

  return {
    title: `${portfolio.fullName} — Portfolio`,
    description: `${portfolio.title} — Professional portfolio generated by CV2Portfolio AI`,
  };
}

export default async function PublicPortfolioPage({ params }: PageProps) {
  const { id } = await params;

  const portfolio = await prisma.portfolio.findUnique({ where: { id } });

  if (!portfolio || portfolio.revoked) {
    notFound();
  }

  const data: PortfolioData = {
    fullName: portfolio.fullName,
    title: portfolio.title,
    bio: portfolio.bio,
    skills: JSON.parse(portfolio.skills),
    education: JSON.parse(portfolio.education),
    experience: JSON.parse(portfolio.experience),
    projects: JSON.parse(portfolio.projects),
    languages: JSON.parse(portfolio.languages),
    contact: JSON.parse(portfolio.contact),
    certifications: JSON.parse(portfolio.certifications),
    theme: JSON.parse(portfolio.theme),
  };

  return <PortfolioView data={data} id={id} />;
}
